from setuptools import setup, find_packages

setup(
    name="compsil",
    version="0.1.1",
    author="Aggelos Semoglou",
    author_email="a.semoglou@outlook.gr",
    description="CompSil: Composite Silhouette for Cluster-Count Selection",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/semoglou/compsil",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.22",
        "pandas>=1.5",
        "scikit-learn>=1.4",
        "matplotlib>=3.6",
        "joblib>=1.2",
    ],
    python_requires=">=3.9",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
    license="MIT",
)
